return {
    "Saghen/blink.cmp",
    enabled = false,
    version = "v0.*",
    opts = {
        highlight = {
            use_nvim_cmp_as_default = true,
        },
        keymap = {
            show = { "<C-space>", "<C-n>" },
            hide = "<C-e>",
            accept = "<cr>",
            select_prev = { "<Up>", "<C-p>" },
            select_next = { "<Down>", "<C-n>" },
            snippet_forward = "<C-l>",
            snippet_backward = "<C-h>",
        },
        accept = { auto_brackets = { enabled = true } },
        kind_icons = {
            Text = "",
            Method = "",
            Function = "",
            Constructor = "",
            Field = "",
            Variable = "",
            Class = "",
            Interface = "",
            Module = "",
            Property = "",
            Unit = "",
            Value = "",
            Enum = "",
            Keyword = "",
            Snippet = "",
            Color = "",
            File = "",
            Reference = "",
            Folder = "",
            EnumMember = "",
            Constant = "",
            Struct = "",
            Event = "",
            Operator = "",
            TypeParameter = "",
        },
    },
}
