return {
    {
        "nvim-treesitter/nvim-treesitter",
        branch = "main",
        build = ":TSUpdate",
        opts = {
            ensure_installed = {
                "bash",
                "c",
                "cmake",
                "cpp",
                "css",
                "dockerfile",
                "fish",
                "git_config",
                "gitcommit",
                "html",
                "hyprlang",
                "ini",
                "javascript",
                "jsdoc",
                "json",
                "jsonc",
                "lua",
                "make",
                "markdown",
                "markdown_inline",
                "nix",
                "printf",
                "python",
                "rasi",
                "regex",
                "svelte",
                "toml",
                "typescript",
                "vim",
                "vimdoc",
                "xml",
                "yaml",
            },
        },
        config = function(_, opts)
            require("nvim-treesitter").install(opts.ensure_installed)
        end,
    },
    {
        "windwp/nvim-ts-autotag",
        event = "LazyFile",
        opts = {
            opts = {
                enable_close = false,
            },
        },
    },
}
